#!/usr/bin/env bash

locker="lightlocker-command"

lock_command="$locker --lock"
suspend_command="systemctl suspend"
reboot_command="systemctl reboot"
poweroff_command="systemctl poweroff"
logout_command="i3-msg exit"

options=$' Lock\n Suspend\n Logout\n Reboot\n Poweroff' 
options_emoji=$' 🔒 Lock\n 💤 Suspend\n 🚫 Logout\n 🔃 Reboot\n ❌ Poweroff'

reboot_now() {
    local reply=$(printf " No\\n No\\n No\\n Yes\\n No" \
        | dmenu -fn "Space Mono" -p "Do you want to reboot?" )
    if [ $reply = "Yes" ]; then
        systemctl reboot
    fi
}

poweroff_now() {
    local reply=$(printf " No\\n No\\n No\\n Yes\\n No" \
        | dmenu -fn "Space Mono" -p "Do you want to shutdown?" )
    if [ $reply = "Yes" ]; then
        systemctl poweroff
    fi
}

response=$(echo "$options_emoji" | dmenu -fn "Space Mono" -p "POWER" | cut -d' ' -f2)
case $response in
    Lock)       $lock_command       ;;
    Suspend)    $suspend_command    ;;
    Logout)     $logout_command     ;;
    Reboot)     reboot_now          ;;
    Poweroff)   poweroff_now        ;;
esac
