#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Adds `~/.local/bin` to $PATH
export PATH=$HOME/.local/bin:$PATH

# Default programs:
export EDITOR="vim"
export TERMINAL="kitty"
export BROWSER="chromium"
export PAGER="less"

# term
if [[ $TERM != "xterm-256color" ]]; then
    TERM="xterm-256color"
fi

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
#export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
#export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
#export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
#export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
#export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
#export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
#export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
#export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
#export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
#export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"

# nnn environment variables
export NNN_OPTS="dEoQxeaU"
export NNN_BMS='d:~/Downloads;'
       NNN_BMS+='s:~/Sandbox;'
       NNN_BMS+='n:~/netshare;'
       NNN_BMS+='p:~/Pictures;'
       NNN_BMS+='u:/run/media;'
       NNN_BMS+='r:~/Repository;'
       NNN_BMS+='c:~/.config;'
export NNN_PLUG='i:imgview;'
       NNN_PLUG+='m:boom;'
       NNN_PLUG+='p:preview-tui;'
       NNN_PLUG+='e:suedit;'
export NNN_COPIER="$XDG_CONFIG_HOME/nnn/copier"
export NNN_COLORS="4231"
export NNN_OPENER="$XDG_CONFIG_HOME/nnn/plugins/nuke"
export NNN_ARCHIVE="\\.(7z|bz2|gz|tar|tgz|zip|rar)$"
export NNN_ORDER='t:$HOME/Downloads'
export NNN_TMPFILE="$XDG_CONFIG_HOME/nnn/.lastd"

# dircolors
eval $(dircolors --sh "$XDG_CONFIG_HOME/shell/dircolors")
