#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send "📶 Wifi connected:" "$(iwgetid -r)" ;;
    3) $DDTERMINAL -e nmtui ;;
esac

[ "$(cat /sys/class/net/w*/operstate)" = 'down' ] && wifiicon="📡"

[ ! -n "${wifiicon+var}" ] && wifiicon=$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')

# printf "%s\n" "$wifiicon"
printf "%s %s\n" "$wifiicon" "$(cat /sys/class/net/e*/operstate | sed "s/down/❎/;s/up/🌐/")"

