#!/bin/sh

case $BLOCK_BUTTON in
    3) $DDTERMINAL -e nmtui ;;
esac

[ "$(cat /sys/class/net/wlan0/operstate)" = 'down' ] && wifiicon="📡"

[ ! -n "${wifiicon+var}" ] && wifiicon=$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')

printf "%s" "$wifiicon"
