#!/bin/bash
# Script to manimpulate pulse audio sink

# Get sink device id
current_card=$(pactl list sinks short | grep "USB" | awk '{print $1}')
[ -z "$current_card" ] && current_card="0"

[ -z "$2" ] && num="5" || num="$2"

send_notification() {
    volume=$(pactl get-sink-volume 0  | awk '{ print $5 }' | cut -d'%' -f1)
    dunstify --timeout 1000 --hints int:value:$volume Volumes
}

case "$1" in
    u*) pactl set-sink-volume $current_card +$num%; send_notification ;;
    d*) pactl set-sink-volume $current_card -$num%; send_notification;;
    m*) pactl set-sink-mute $current_card toggle ;;
esac
