#!/bin/bash
# Simple script to take screenshoot and send a notification

PHOTO_ICON_PATH=$HOME/Pictures/misc/camera.png

take_ss() {
    local option=$1
    scrot '%Y-%m-%d_%H%M%S.png' -e 'mv $f ~/Pictures/Screenshoot/' \
    	$option 2> /dev/null
}

notify_send() {
    notify-send --expire-time=2000 -i view-fullscreen \
        "$@" --icon=$PHOTO_ICON_PATH \
	&& sleep 0.5
}

if ! [ -x "$(command -v scrot)" ]; then
    notify_send 'Screenshoot fail' 'scrot not installed'
    exit 1
fi

main() {
    case "$1" in
	crop)
            notify_send 'Screenshoot!' 'Select area to capture.'
            take_ss -s
            notify_send 'Screenshoot!' 'Saved to ~/Pictures/Screenshoots/scrot!'
            ;;
        *)
            take_ss && \
            notify_send 'Screenshoot!' 'Saved to ~/Pictures/Screenshoots/scrot!'
            ;;
    esac
}

main "$@"
